name: Build and publish NuGet package

on:
  push:
    tags:
      - 'v*.*.*'  # 태그가 vX.X.X 형식일 때만 실행
  workflow_dispatch: # This line allows manual triggering

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore BlittableChecker.sln

      - name: Build
        run: dotnet build BlittableChecker.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test BlittableChecker.sln --no-restore --verbosity normal
          
      # NuGet publish
      - name: Pack
        run: |
          dotnet pack BlittableChecker/BlittableChecker.csproj --configuration Release --no-build --output ./nupkgs
          dotnet pack BlittableCheckerGenerator/BlittableCheckerGenerator.csproj --configuration Release --no-build --output ./nupkgs
        
      - name: Add GitHub Source
        run: dotnet nuget add source "https://nuget.pkg.github.com/breadpack/index.json" --name "github" --username OWNER --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text

      - name: Publish to GitHub Packages
        run: dotnet nuget push ./nupkgs/*.nupkg --source "github" --skip-duplicate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
