name: Build and publish NuGet package

on:
  push:
    tags:
      - 'v*.*.*'  # 태그가 vX.X.X 형식일 때만 실행
  workflow_dispatch: # This line allows manual triggering

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore BlittableChecker.sln

      - name: Build
        run: dotnet build BlittableChecker.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test BlittableChecker.sln --no-restore --verbosity normal
          
      # NuGet publish
      - name: Pack
        run: |
          dotnet pack BlittableChecker/BlittableChecker.csproj --configuration Release --no-build --output ./nupkgs
          dotnet pack BlittableCheckerGenerator/BlittableCheckerGenerator.csproj --configuration Release --no-build --output ./nupkgs

      - name: Publish the package
        run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
